# Generated by Django 3.0.5 on 2020-04-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('sm', 'small'), ('lg', 'large')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('reg', 'Regular Pizza'), ('sic', 'Sicilian Pizza')], max_length=64),
        ),
    ]
