# Generated by Django 3.0.5 on 2020-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200412_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner_platters',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dinner_platters',
            name='size',
        ),
        migrations.AddField(
            model_name='dinner_platters',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner_platters',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
