# Generated by Django 3.0.5 on 2020-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200413_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
