# Generated by Django 3.0.5 on 2020-04-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200413_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
