# Generated by Django 3.0.5 on 2020-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('additions', models.ManyToManyField(blank=True, to='orders.Addition')),
                ('dinner_platters', models.ManyToManyField(blank=True, to='orders.Dinner_Platters')),
                ('pastas', models.ManyToManyField(blank=True, to='orders.Pasta')),
                ('pizzas', models.ManyToManyField(blank=True, to='orders.Pizza')),
                ('salads', models.ManyToManyField(blank=True, to='orders.Salad')),
                ('subs', models.ManyToManyField(blank=True, to='orders.Subs')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Toppings')),
            ],
        ),
    ]
