# Generated by Django 3.0.5 on 2020-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200423_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
    ]
