# Generated by Django 3.0.5 on 2020-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_toppings_pizzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='subs',
            field=models.ManyToManyField(blank=True, to='orders.Subs'),
        ),
    ]
