# Generated by Django 3.0.5 on 2020-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_addition_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='subs',
            name='additions',
            field=models.ManyToManyField(blank=True, to='orders.Addition'),
        ),
    ]
