# Generated by Django 3.0.5 on 2020-04-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200428_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['type']},
        ),
        migrations.AlterField(
            model_name='cart',
            name='additions',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Addition'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='dinner_platters',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Dinner_Platters'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pastas',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='salads',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Salad'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, choices=[('sm', 'small'), ('lg', 'large')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Subs'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Toppings'),
        ),
    ]
