# Generated by Django 3.0.5 on 2020-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200429_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Toppings'),
        ),
    ]
