# Generated by Django 3.0.5 on 2020-04-30 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0020_auto_20200430_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('salad', models.ManyToManyField(to='orders.Salad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_salad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dinner_platter', models.ManyToManyField(to='orders.Dinner_Platters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_platter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pasta', models.ManyToManyField(to='orders.Pasta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_pasta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
