# Generated by Django 3.0.5 on 2020-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200430_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpasta',
            name='category',
            field=models.CharField(default='pasta', max_length=20),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='category',
            field=models.CharField(default='pizza', max_length=20),
        ),
        migrations.AddField(
            model_name='orderplatter',
            name='category',
            field=models.CharField(default='platter', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='category',
            field=models.CharField(default='salad', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='category',
            field=models.CharField(default='sub', max_length=20),
        ),
    ]
