# Generated by Django 3.0.5 on 2020-05-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200502_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orderpasta',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Checkouts'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Checkouts'),
        ),
        migrations.AddField(
            model_name='orderplatter',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Checkouts'),
        ),
        migrations.AddField(
            model_name='ordersalad',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Checkouts'),
        ),
        migrations.AddField(
            model_name='ordersub',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Checkouts'),
        ),
    ]
