# Generated by Django 3.0.5 on 2020-05-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_checkouts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersub',
            old_name='additons',
            new_name='additions',
        ),
    ]
